SELECT ID, NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, CPF FROM
		(SELECT ROW_NUMBER() OVER (ORDER BY ID) AS Row, ID, NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, CPF FROM CLIENTES WITH(NOLOCK))
		AS ClientesWithRowNumbers
	--WHERE Row > @iniciarEm AND Row <= (@iniciarEm+@quantidade) ORDER BY